In [2]:
import numpy as np

## 05 - AUTOVALOR e AUTOVETOR

$A \overrightarrow{v} = λ\overrightarrow{v}$ \
$A \overrightarrow{v} - (λ I) \overrightarrow{v} = 0 $\
$(A - λ I) \overrightarrow{v}= 0 $\
$det(A - λ I) = 0 $




In [3]:
A = np.array([[0, 0.95, 0.05], [0.9, 0, 0.1], [0.7, 0.3, 0]]) # ex
w, v = np.linalg.eig(A)   # w = autovalor / v = autovetor 

# propabilidade das bikes
p = np.array([[0, 0.95, 0.7],   # cada LINHA é a prob de cada estacao ir para a linha
              [0.9, 0, 0.3],    # no caso, a primeira linha é a 1a estacao, ent a 1a tem 0
              [0.1, 0.05, 0]])  # prob de ir pra ela mesma, a 2a tem 0.95 de ir pra 1a e a 
                                # 3a tem 0.7 de ir pra 1a
# n de bikes
b = np.array([[10],
              [10],
              [10]])

for _ in range(100):
  b = p @ b
b

array([[14.34180597],
       [13.54638245],
       [ 2.11181158]])

encontramos um sistema estavel, pq o valor MAXIMO dos autovalores é 1:

- array([ 1.        , -0.91231056, -0.08768944])


podemos usar desta informacao para analisar se o sistea é estavel ou nao

# Ex CARCARAS e SAPOS
**Objetivo: auto-vetores e auto-valores como pontos de estabilidade, expansão, ou colapso**

 Vamos retomar o problema da população de carcarás e de sapos no Capítulo 2. Nesse problema, tínhamos a situação em que carcarás estão no mesmo habitat que sapos, obedecendo às seguintes regras:

* A população de carcarás naturalmente cai em 20% a cada mês
* Para cada cinco mil sapos existentes naquele mês, um novo carcará nasce
* A população de sapos naturalmente sobe em 10% porque eles se reproduzem
* A cada mês, cada carcará consegue comer 100 sapos

Isso significa que podemos escrever equações para calcular o número de carcarás e de sapos a cada mês, tomando por base a quantidade deles no mês anterior:

$$ 
\begin{cases}
    \begin{aligned}
    c_t & = 0.8 c_{t-1} + 0.2 s_{t-1} \\
    s_t & = - 0.1 c_{t-1} + 1.1 s_{t-1} \\
    \end{aligned}
\end{cases}
$$

Podemos fazer esse cálculo usando a operação matricial:
$$
\begin{bmatrix}
    c_t \\
    s_t 
\end{bmatrix}
=
\begin{bmatrix}
    0.8 & 0.2\\
    -0.1 & 1.1
\end{bmatrix} 
\begin{bmatrix}
    c_{t-1} \\
    s_{t-1}
\end{bmatrix}
$$

Como já vimos, podemos calcular a dinâmica da população ao longo do tempo partindo, por exemplo, de 600 carcarás e 500 mil sapos:

In [4]:

# 1/5 é pq estamos tratando os sapos em MILHARES!
p = np.array([[0.8, 1/5],
              [-0.1, 1.1]])


# escrevemos 600 / 500 e NAO 600 / 500.000 porque os sapos sao representados em MILHARES!!!
cs = np.array([[600], 
               [500]])  


w, v = np.linalg.eig(A)

print(w)
print('-')
print(v)

# aqui conseguimos ver que pelo primeiro vetor ter valor 1, o sistema NAO vai colapsar, vai entrar em 
# uma constante, podemos tambem usar o primeiro vetor (linha da esquerda), para achar a proporcao!

# colapso / equilibrio / explosao

[ 1.         -0.91231056 -0.08768944]
-
[[-0.57735027 -0.69213549 -0.10624252]
 [-0.57735027  0.64793959 -0.04247924]
 [-0.57735027  0.31799803  0.99343245]]


# Explicacao para achar a matriz a partir dos autovalores e autovetores
*Objetivo: encontrar uma matriz à partir de seus auto-valores e auto-vetores*

Em algumas situações (por exemplo, quando estou montando essa lista de exercícios - mas, de forma mais geral, quando estamos projetando sistemas dinâmicos), gostaríamos de encontrar matrizes que têm os autovalores e autovetores que queremos. Para isso, vamos escrever a equação de autovetores e autovalores na forma matricial.

Quando estamos falando de somente um auto-vetor, podemos escrever:

$$
Ax = x \lambda
$$

Porém, se tivermos dois auto-vetores, e seus auto-valores correspondentes, temos na verdade um sistema:

$$
\begin{cases}
Ax_1 = x_1 \lambda_1 \\
Ax_2 = x_2 \lambda_2 
\end{cases}
$$

Esse sistema pode ser escrito na forma de uma multiplicação matricial, se assumirmos que nossos auto-vetores são vetores-coluna:

$$
A \begin{bmatrix} x_1 & x_2 \end{bmatrix} = \begin{bmatrix} x_1 & x_2 \end{bmatrix} \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix} 
$$

Multiplicando os dois lados da equação por $\begin{bmatrix} x_1 & x_2 \end{bmatrix}^{-1}$, ficamos com:

$$
A \begin{bmatrix} x_1 & x_2 \end{bmatrix}\begin{bmatrix} x_1 & x_2 \end{bmatrix}^{-1} = \begin{bmatrix} x_1 & x_2 \end{bmatrix} \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix} \begin{bmatrix} x_1 & x_2 \end{bmatrix}^{-1}
$$

e, portanto:
$$
A = \begin{bmatrix} x_1 & x_2 \end{bmatrix} \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix} \begin{bmatrix} x_1 & x_2 \end{bmatrix}^{-1}
$$

Por exemplo, se quiséssemos uma matriz cujos auto-valores são $0.7$ e $0.2$ e os auto-vetores correspondentes são $[1,0]^T$ e $[0.5, 0.5]^T$, então deveríamos calcular:

$$
A = \begin{bmatrix} 1 & 0.5 \\ 0 & 0.5 \end{bmatrix} \begin{bmatrix} 0.7 & 0 \\ 0  & 0.2 \end{bmatrix} \begin{bmatrix} 1 & 0.5 \\ 0 & 0.5 \end{bmatrix}^{-1}
$$

Encontre a matriz com autovetores $[1,0]^T$ e $[0.5, 0.5]^T$ e autovalores $0.7$ e $0.2$.

In [5]:
S = np.array( [[1, 0], [0.5, 0.5]]).T
L = np.array( [ [0.7, 0], [0, 0.2] ])
S @ L @ np.linalg.inv(S)

array([[ 0.7, -0.5],
       [ 0. ,  0.2]])

### COVARIANCIA

In [6]:
# Dados de exemplo
dados = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Cálculo da matriz de covariância
covariancia = np.cov(dados, rowvar=False)

print("Matriz de Covariância:\n", covariancia)

Matriz de Covariância:
 [[9. 9. 9.]
 [9. 9. 9.]
 [9. 9. 9.]]


### SVD

In [10]:
import numpy as np

# Matriz de exemplo
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Cálculo da SVD
u, s, vt = np.linalg.svd(A)

print("Matriz U:\n", u)
print("Sigma:", s)
print("Matriz V transposta:\n", vt)


Matriz U:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Sigma: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
Matriz V transposta:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
